version: "3.4"

services:
  app:
    image: registry.gitlab.com/huykhoiqc/youtube-quiz-api
    volumes:
      - ./:/app
    environment:
      - ROUTE_PREFIX=${ROUTE_PREFIX}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - MONGOOSE_PATH=${MONGOOSE_PATH}
      - CONTROLLER_DIR=${CONTROLLER_DIR}
      - MIDDLEWARE_DIR=${MIDDLEWARE_DIR}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
