export enum MsgError {
  INVALID_TOKEN = "INVALID_TOKEN",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  CHANNEL_EXISTED = "CHANNEL_EXISTED",
  CHANNEL_NOT_EXIST_IN_YOUTUBE = "CHANNEL_NOT_EXIST_IN_YOUTUBE",
  CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND",
}
