export enum MsgError {
  INVALID_TOKEN = "INVALID_TOKEN",

  USER_NOT_FOUND = "USER_NOT_FOUND",

  VIDEO_NOT_FOUND = "VIDEO_NOT_FOUND",
  VIDEO_QUIZ_NOT_EXTRACTED = "VIDEO_QUIZ_NOT_EXTRACTED",
  VIDEO_NOT_CONFIG_TO_PLAY = "VIDEO_NOT_CONFIG_TO_PLAY",
  CHANNEL_EXISTED = "CHANNEL_EXISTED",
  CHANNEL_NOT_EXIST_IN_YOUTUBE = "CHANNEL_NOT_EXIST_IN_YOUTUBE",
  CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND",
}
